---
title: "final"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(sf)
library(mapview)
library(tmap)
library(leaflet)
library(rosm)
library(prettymapr)
library(kableExtra)
library(xtable)
library(sjPlot)
library(webshot)
library(gt)
```

```{r, cruise data}
# read in cruise data
NMFS_transect <- read_csv(here("data", "table_257.csv")) %>% 
  clean_names()

NMFS_obs <- read_csv(here("data", "table_258.csv")) %>% 
  clean_names()
```

```{r, band data}
# read in banding data
laal_hi_band <- read_csv(here("data", "laal_hi_bbl2021_bnd_enc.csv")) 

laal_ca_band <- read_csv(here("data", "laal_ca_bbl2021_bnd_enc.csv")) 

albie_all_band <- read_csv(here("data", "laal_bfal_ca_hi_bbl2021.csv")) #both bfal and laal banding data for CA and HI
```

```{r}
# explore banding data
# unique(albie_all_band$event_year)
# head(albie_all_band)
#unique(albie_all_band$species_name)
#unique(albie_all_band$event_date)
#class(albie_all_band$event_date)
```

```{r}
#combine cruise observation data 

nmfs_data <- NMFS_obs %>%
  inner_join(NMFS_transect, by = "gis_key")

```

```{r}
# save new nmfs cruise data 
write.csv(nmfs_data, file = file.choose(new = T))
```

```{r}
nmfs_data <- nmfs_data %>% 
  mutate(year = year(date)) %>% 
  relocate(year, .before = date)
```

```{r}
nmfs_data <- nmfs_data %>% 
  mutate(common_name = "") %>% 
  filter(species == c("BFAL", "LAAL")) %>% 
  relocate(common_name, .after = species)
```

```{r}
nmfs_data <- nmfs_data %>% 
  mutate(common_name = case_when(
    species == "BFAL" ~ "Black-footed albatross",
    species == "LAAL" ~ "Laysan albatross")
  )

#head(nmfs_data)
```

```{r}
laal_hi_band <- laal_hi_band %>% 
  mutate(species = "LAAL") %>% 
  relocate(species, .after = original_band) %>% 
  relocate(species_name, .after = species) %>% 
  relocate(species_scientific_name, .after = species_name) %>%
  mutate(count = "1") %>% 
  relocate(count, .after = species_scientific_name) #%>% 
  #select(c(-other_bands, -who_obtained_code))
  
```

```{r}
laal_ca_band <- laal_ca_band %>% 
  mutate(species = "LAAL") %>% 
  relocate(species, .after = original_band) %>% 
  relocate(species_name, .after = species) %>% 
  relocate(species_scientific_name, .after = species_name) %>% 
  mutate(count = "1") %>% 
  relocate(count, .after = species_scientific_name) %>% 
  select(c(-other_bands, -who_obtained_code))
```

```{r}
albie_all_band <- albie_all_band %>% 
  mutate(species = case_when(
    species_scientific_name == "Phoebastria immutabilis" ~ "LAAL",
    species_scientific_name == "Phoebastria nigripes" ~ "BFAL")) %>% 
  relocate(species, .after = original_band) %>% 
  relocate(species_name, .after = species) %>% 
  relocate(species_scientific_name, .after = species_name) %>% 
  mutate(count = as.numeric("1")) %>% 
  relocate(count, .after = species_scientific_name) %>% 
  mutate(event_date = as.Date(event_date, "%m/%d/%y")) %>% 
  rename(year = event_year) #%>% 
  select(c(-other_bands, -who_obtained_code))
 
```

```{r}
# convert databases to sf element to create geom
nmfs_sf <- st_as_sf(nmfs_data, 
                    coords = c("longitude_mid_o","latitude_mid_o"), 
                    crs = 4326)

laal_ca_sf <- st_as_sf(laal_ca_band, 
                       coords = c("lon_dd","lat_dd"), 
                       crs = 4326)

laal_hi_sf <- st_as_sf(laal_hi_band, 
                       coords = c("lon_dd","lat_dd"), 
                       crs = 4326)

albie_sf <- st_as_sf(albie_all_band, 
                       coords = c("lon_dd","lat_dd"), 
                       crs = 4326)

```

```{r}
# bbox_ca <- searchbbox("California")
# 
# osm.plot(bbox_ca)
```

```{r}
# tmap_mode("view")
# tm_shape(nmfs_sf) +
#   tm_dots("species") +
#   #tm_basemap("Stamen.Terrain") +
#   bmaps.plot(bbox_ca)
```

```{r}
nmfs_map <-  mapview(nmfs_sf,
                      map.types = c("Stamen.Terrain"),
                      layer.name = "NMFS CA Albatross",
                      col.regions = "#F757E1")

nmfs_map
```

```{r}
# mapview(albie_sf,
#         map.types = c("Stamen.Terrain"),
#         layer.name = "Laysan and Black-footed albatross",
#         col.regions = "#F757E1") 

```

```{r}

nmfs_count <- nmfs_data %>% 
  group_by(species, date) %>% 
  summarise(total = sum(count))

```

```{r}
#nmfs_count$year <- nmfs_count$date 

nmfs_count_yr <- separate(nmfs_count, col = year, into = c('yr', 'mth', 'day'), sep = '-', convert = TRUE) %>% 
  select(c(-mth, -day)) %>% 
  relocate(yr, .before = date) %>% 
  rename(year = yr) %>% 
  group_by(species, year) %>% 
  summarise(total_obs = sum(total))

```

```{r}
nmfs_plot <- ggplot(nmfs_count_yr, aes(x = year, y = total_obs, group = species)) +
  geom_point(aes(color = species,
                 shape = species)) +
  geom_line(aes(color = species)) +
  scale_color_manual(name = "Albatross species",
                     values = c("#9E7E8C", "#39ACB1"),
                     labels = c("Black-footed Albatross", "Laysan Albatross")) +
  geom_vline(xintercept = 2011,
             linetype = "solid",
             color = "goldenrod1",
             size = 2) +
  labs(title = "NOAA NMFS CA Cruise Albatross Observations",
       x = "Cruise Year",
       y = "Total Albatross Observed") +
  guides(shape = FALSE) +
  annotate("text",
           label = "Tōhoku tsunami",
           x = 2014.5,
           y = 425,
           color = "black",
           size = 4) +
  theme_minimal() +
  theme(legend.background = element_blank(),
        legend.position = "bottom")

nmfs_plot
```

```{r}
ggsave("images/nmfs_plot.png",
       width = 4,
       height = 4,
       units = "in",
       bg = "white",
       dpi = "print")
```

```{r}

band_count <- albie_all_band %>% 
  group_by(species, year) %>% 
  summarise(total = sum(count))

```

```{r}
#plot banding data

band_plot <- ggplot(band_count, aes(x = year, y = total, group = species)) +
  geom_point(aes(color = species,
                 shape = species)) +
  geom_line(aes(color = species)) +
  scale_color_manual(name = "Albatross species",
                     values = c("#9E7E8C", "#39ACB1"),
                     labels = c("Black-footed Albatross", "Laysan Albatross")) +
  geom_vline(xintercept = 2011,
             linetype = "solid",
             color = "goldenrod1",
             size = 2) +
  guides(shape = FALSE) +
  annotate("text",
           label = "Tōhoku tsunami",
           x = 2014,
           y = 4700,
           color = "black",
           size = 4) +
  labs(title = "Hawaii & California Albatross Banding Effort",
       x = "Year",
       y = "Albatross Banded",
       color = "Species") +
  theme_minimal() +
  theme(legend.background = element_blank(),
        legend.position = "bottom")  
  
band_plot
```

```{r}
ggsave("images/band_plot.png",
       width = 4,
       height = 4,
       units = "in",
       bg = "white",
       dpi = "print")
```

```{r}
# create two band count dataframes based on species
bfal_band <- split(band_count, band_count$species)[[1]]
laal_band <- split(band_count, band_count$species)[[2]]
```

```{r}
# explore population data 1996 - 2021

bfal_mean <- round(mean(bfal_band$total), 2)
bfal_min <- round(min(bfal_band$total), 2)
bfal_max <- round(max(bfal_band$total), 2)

laal_mean <- round(mean(laal_band$total), 2)
laal_min <- round(min(laal_band$total), 2)
laal_max <- round(max(laal_band$total), 2)

```

```{r}
bfal_qqplot <- ggplot(bfal_band) +
  geom_qq(aes(sample = total),
          color = "#9E7E8C",
          size = 3) +
  geom_qq_line(aes(sample = total),
            color = "grey") +
  xlab("Normal distribution quantiles") +
  ylab("Sample quantiles") +
  labs(title = "Black-footed Albatross QQ Plot") +
  theme_minimal() +
  theme(line = element_blank(),
        panel.grid = element_blank(),
        strip.text = element_blank(),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "none")
bfal_qqplot  
  
```

```{r}
ggsave("images/bfal_qqplot.png",
       width = 4,
       height = 4,
       units = "in",
       bg = "white",
       dpi = "print")
```

```{r}
laal_qqplot <- ggplot(laal_band) +
  geom_qq(aes(sample = total),
          color = "#39ACB1",
          size = 3) +
  geom_qq_line(aes(sample = total),
            color = "grey") +
  xlab("Normal distribution quantiles") +
  ylab("Sample quantiles") +
  labs(title = "Laysan Albatross QQ Plot") +
  theme_minimal() +
  theme(line = element_blank(),
        panel.grid = element_blank(),
        strip.text = element_blank(),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "none")
laal_qqplot  
```

```{r}
ggsave("images/laal_qqplot.png",
       width = 4,
       height = 4,
       units = "in",
       bg = "white",
       dpi = "print")
```

```{r}
# filter species by pre and post tsunami event
bfal_pre <- bfal_band %>% 
  filter(year %in% c(2002:2010))

bfal_post <- bfal_band %>% 
  filter(year %in% c(2011:2020))

laal_pre <- laal_band %>% 
  filter(year %in% c(2002:2010))

laal_post <- laal_band %>% 
  filter(year %in% c(2011:2020))

```

```{r}
# mean population of species pre and post tsunami event

mean_pre_bfal <- round(mean(bfal_pre$total), 2)
mean_post_bfal <- round(mean(bfal_post$total), 2)

mean_pre_laal <- round(mean(laal_pre$total), 2)
mean_post_laal <- round(mean(laal_post$total), 2)

```

```{r}

pop_mean <- tibble(species = c("BFAL", "LAAL"),
                       mean_pre = c(mean_pre_bfal, mean_pre_laal),
                       mean_post = c(mean_post_bfal, mean_post_laal))

pop_mean_table <- knitr::kable(pop_mean,
                               col.names = c('Species', 'Pre_Pop_Mean', 'Post_Pop_Mean'),
                               caption = "Albatross Population Means Pre & Post Tōhoku Tsunami") %>% 
  as_image(width = 4)

pop_mean_table
```

```{r}
# save mean population data 
write.csv(pop_mean, file = file.choose(new = T))

```

$$ \text{Albatross population trend}_i = \beta_0 + \beta_1 \text{time since tsunami}_i + \varepsilon_i $$

```{r}

bfal_lm <- summary(lm(total ~ year, data = bfal_post)) %>% 
  #xtable() %>% 
  #kable(caption = "Simple Linear Regression - Albatross population post-tsunami") #%>% 
  #save_kable(file = "bfal_lm.png")
  tab_model(title = "Simple Linear Regression - Black-footed Albatross population post-tsunami",
    file = "bfal_lm_tab.html") 
  
bfal_lm 
```

```{r}

laal_lm <- summary(lm(total ~ year, data = laal_post)) %>% 
  #xtable() %>% 
  #kable(caption = "Simple Linear Regression - Albatross population post-tsunami") #%>% 
  #save_kable(file = "bfal_lm.png")
  tab_model(title = "Simple Linear Regression - Laysan Albatross population post-tsunami",
    file = "laal_lm_tab.html") 
  
laal_lm 
```

```{r}
# save simple linear regressions to png

webshot("bfal_lm_tab.html", "bfal_lm_tab.png")
```

